export default [
  {
    name: 'Registration',
    duration: 40,
  },
  // Hall 1
  [
    {
      name: 'Opening',
      duration: 20,
    },
        {
      name: 'Dependency Injection in JavaScript Frameworks',
      speakerId: 'armen',
      duration: 50,
      levels: [1, 2],
      lang: 'am',
    },
    {
      name: 'Node.js and GenAI: Deep Dive into the RAG Architecture',
      speakerId: 'arthur',
      duration: 35,
      levels: [1,2],
      lang: 'am',
    },
    {
      name: 'Debugging with DevTools: Mastering the Detective Work',
      speakerId: 'lilit',
      duration: 35,
      levels: [],
      lang: 'am',
    },
    {
      name: 'Break',
      duration: 15,
    },
    {
      name: 'Let\'s Not Get Hacked',
      speakerId: 'davit',
      duration: 30,
      levels: [1, 2],
      lang: 'am',
    },
    {
      name: 'Break',
      duration: 15,
    },
    {
      name: 'Rust for JavaScript Programmers',
      speakerId: 'vahe',
      duration: 45,
      levels: [],
      lang: 'am',
    },
    {
      name: 'Break',
      duration: 30,
    },
    {
      name: 'System Design Fundamentals',
      speakerId: 'arpi',
      duration: 45,
      levels: [],
      lang: 'am',
    },
    {
      name: 'Break',
      duration: 15,
    },
    {
      name: 'Logic with Advanced TypeScript Types',
      speakerId: 'erik',
      duration: 45,
      levels: [2],
      lang: 'am',
    },
    {
      name: 'Break',
      duration: 15,
    },
    {
      name: 'Programming Practices for Developing High-Quality Software',
      speakerId: 'rouben',
      duration: 45,
      levels: [],
      lang: 'am',
    },
    {
      name: 'Closing',
      duration: 30,
    },
    {
      name: 'Afterparty',
      duration: 30,
    },
  ],
  // BlackBox
  // [
  //   {
  //     name: '',
  //     duration: 30,
  //   },
  //   {
  //     name: 'JavaScript and Game Development',
  //     speakerId: 'arsen',
  //     duration: 35,
  //     levels: [],
  //     lang: 'am',
  //     videoUrl: 'https://bit.ly/3uijVhJ',
  //   },
  //   {
  //     name: 'Nuxt 3. What\'s new?',
  //     speakerId: 'vasiliy',
  //     duration: 35,
  //     levels: [1, 2],
  //     lang: 'ru',
  //     videoUrl: 'https://bit.ly/3tvTdDe',
  //   },
  //   {
  //     name: 'Audio and video manipulation',
  //     speakerId: 'david',
  //     duration: 35,
  //     levels: [],
  //     lang: 'am',
  //     videoUrl: 'https://bit.ly/36eH9xx',
  //   },
  //   {
  //     name: 'Control a drone with JavaScript',
  //     speakerId: 'suren',
  //     duration: 35,
  //     levels: [0, 1],
  //     lang: 'am',
  //     videoUrl: 'https://bit.ly/3N9Ut6T',
  //   },
  //   {
  //     name: 'Break',
  //     duration: 70,
  //   },
  //   {
  //     name: 'Why you should definitely use NgRx',
  //     speakerId: 'armenv',
  //     duration: 35,
  //     levels: [1, 2],
  //     lang: 'en',
  //     videoUrl: 'https://bit.ly/3ty16b6',
  //   },
  //   {
  //     name: 'The World Beyond console.log',
  //     speakerId: 'davit',
  //     duration: 35,
  //     levels: [],
  //     lang: 'am',
  //     videoUrl: 'https://bit.ly/3uheUGl',
  //   },
  //   {
  //     name: 'Local State and Server Cache: Finding a Balance',
  //     speakerId: 'natalia',
  //     duration: 30,
  //     levels: [1],
  //     lang: 'en',
  //     videoUrl: 'https://bit.ly/3qqjqkw',
  //   },
  //   {
  //     name: 'Break',
  //     duration: 20,
  //   },
  //   {
  //     name: 'Event Store - Cool replacement for React Context',
  //     speakerId: 'elmira',
  //     duration: 35,
  //     levels: [1, 2],
  //     lang: 'am',
  //     videoUrl: 'https://bit.ly/3ty16b6',
  //   },
  //   {
  //     name: 'Micro-frontend has entered the game',
  //     speakerId: 'vitaly',
  //     duration: 35,
  //     levels: [1],
  //     lang: 'ru',
  //     videoUrl: 'https://bit.ly/3JA4Gay',
  //   },
  // ],
];
